void delta_hists()
{
//=========Macro generated from canvas: c1/c1
//=========  (Mon May 28 23:58:57 2018) by ROOT version 6.12/06
   TCanvas *c1 = new TCanvas("c1", "c1",0,64,1191,704);
   gStyle->SetOptStat(0);
   c1->Range(0.904,-26.5125,1.064,238.6125);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.125);
   c1->SetRightMargin(0.125);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("Radiative correction factors");
   
   TH1F *_stack_1 = new TH1F("_stack_1","Radiative correction factors",100,0.924,1.044);
   _stack_1->SetMinimum(0);
   _stack_1->SetMaximum(212.1);
   _stack_1->SetDirectory(0);
   _stack_1->SetStats(0);
   _stack_1->SetLineWidth(2);
   _stack_1->GetXaxis()->SetTitle("#delta_{D}/#delta_{A}");
   _stack_1->GetXaxis()->SetLabelFont(22);
   _stack_1->GetXaxis()->SetLabelSize(0.05);
   _stack_1->GetXaxis()->SetTitleSize(0.05);
   _stack_1->GetXaxis()->SetTitleOffset(0.86);
   _stack_1->GetXaxis()->SetTitleFont(22);
   _stack_1->GetYaxis()->SetTitle("dN/dx");
   _stack_1->GetYaxis()->SetLabelFont(22);
   _stack_1->GetYaxis()->SetLabelSize(0.05);
   _stack_1->GetYaxis()->SetTitleSize(0.05);
   _stack_1->GetYaxis()->SetTitleFont(22);
   _stack_1->GetZaxis()->SetLabelFont(22);
   _stack_1->GetZaxis()->SetLabelSize(0.05);
   _stack_1->GetZaxis()->SetTitleSize(0.05);
   _stack_1->GetZaxis()->SetTitleFont(22);
   ->SetHistogram(_stack_1);
   
   
   TH1F *hC_stack_1 = new TH1F("hC_stack_1","#delta_{D}/#delta_{C}",100,0.9955,1.0285);
   hC_stack_1->SetBinContent(8,4);
   hC_stack_1->SetBinContent(10,2);
   hC_stack_1->SetBinContent(11,2);
   hC_stack_1->SetBinContent(12,8);
   hC_stack_1->SetBinContent(13,28);
   hC_stack_1->SetBinContent(14,144);
   hC_stack_1->SetBinContent(15,46);
   hC_stack_1->SetBinContent(16,30);
   hC_stack_1->SetBinContent(17,22);
   hC_stack_1->SetBinContent(18,18);
   hC_stack_1->SetBinContent(19,22);
   hC_stack_1->SetBinContent(20,20);
   hC_stack_1->SetBinContent(21,16);
   hC_stack_1->SetBinContent(22,4);
   hC_stack_1->SetBinContent(23,4);
   hC_stack_1->SetBinContent(26,2);
   hC_stack_1->SetBinContent(27,2);
   hC_stack_1->SetBinContent(88,2);
   hC_stack_1->SetBinContent(89,2);
   hC_stack_1->SetBinContent(90,2);
   hC_stack_1->SetBinContent(91,2);
   hC_stack_1->SetBinContent(92,2);
   hC_stack_1->SetEntries(384);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff0000");
   hC_stack_1->SetLineColor(ci);
   hC_stack_1->SetLineWidth(2);
   hC_stack_1->GetXaxis()->SetTitle("Fact_ex/tC.Fact_ex");
   hC_stack_1->GetXaxis()->SetRange(1,100);
   hC_stack_1->GetXaxis()->SetLabelFont(22);
   hC_stack_1->GetXaxis()->SetLabelSize(0.05);
   hC_stack_1->GetXaxis()->SetTitleSize(0.05);
   hC_stack_1->GetXaxis()->SetTitleFont(22);
   hC_stack_1->GetYaxis()->SetLabelFont(22);
   hC_stack_1->GetYaxis()->SetLabelSize(0.05);
   hC_stack_1->GetYaxis()->SetTitleSize(0.05);
   hC_stack_1->GetYaxis()->SetTitleFont(22);
   hC_stack_1->GetZaxis()->SetLabelFont(22);
   hC_stack_1->GetZaxis()->SetLabelSize(0.05);
   hC_stack_1->GetZaxis()->SetTitleSize(0.05);
   hC_stack_1->GetZaxis()->SetTitleFont(22);
   ->Add(hC_stack_1,"");
   
   TH1F *hPb_stack_2 = new TH1F("hPb_stack_2","#delta_{D}/#delta_{Pb}",100,0.989,1.044);
   hPb_stack_2->SetBinContent(8,2);
   hPb_stack_2->SetBinContent(11,4);
   hPb_stack_2->SetBinContent(12,2);
   hPb_stack_2->SetBinContent(13,6);
   hPb_stack_2->SetBinContent(15,2);
   hPb_stack_2->SetBinContent(16,2);
   hPb_stack_2->SetBinContent(17,6);
   hPb_stack_2->SetBinContent(19,4);
   hPb_stack_2->SetBinContent(20,74);
   hPb_stack_2->SetBinContent(21,102);
   hPb_stack_2->SetBinContent(22,42);
   hPb_stack_2->SetBinContent(23,32);
   hPb_stack_2->SetBinContent(24,22);
   hPb_stack_2->SetBinContent(25,18);
   hPb_stack_2->SetBinContent(26,10);
   hPb_stack_2->SetBinContent(27,16);
   hPb_stack_2->SetBinContent(28,6);
   hPb_stack_2->SetBinContent(29,10);
   hPb_stack_2->SetBinContent(30,8);
   hPb_stack_2->SetBinContent(33,2);
   hPb_stack_2->SetBinContent(36,4);
   hPb_stack_2->SetBinContent(56,2);
   hPb_stack_2->SetBinContent(71,2);
   hPb_stack_2->SetBinContent(80,2);
   hPb_stack_2->SetBinContent(89,2);
   hPb_stack_2->SetBinContent(93,2);
   hPb_stack_2->SetEntries(384);
   hPb_stack_2->SetLineWidth(2);
   hPb_stack_2->GetXaxis()->SetTitle("Fact_ex/tPb.Fact_ex");
   hPb_stack_2->GetXaxis()->SetRange(1,100);
   hPb_stack_2->GetXaxis()->SetLabelFont(22);
   hPb_stack_2->GetXaxis()->SetLabelSize(0.05);
   hPb_stack_2->GetXaxis()->SetTitleSize(0.05);
   hPb_stack_2->GetXaxis()->SetTitleFont(22);
   hPb_stack_2->GetYaxis()->SetLabelFont(22);
   hPb_stack_2->GetYaxis()->SetLabelSize(0.05);
   hPb_stack_2->GetYaxis()->SetTitleSize(0.05);
   hPb_stack_2->GetYaxis()->SetTitleFont(22);
   hPb_stack_2->GetZaxis()->SetLabelFont(22);
   hPb_stack_2->GetZaxis()->SetLabelSize(0.05);
   hPb_stack_2->GetZaxis()->SetTitleSize(0.05);
   hPb_stack_2->GetZaxis()->SetTitleFont(22);
   ->Add(hPb_stack_2,"");
   
   TH1F *hFe_stack_3 = new TH1F("hFe_stack_3","#delta_{D}/#delta_{Fe}",100,0.924,1.023);
   hFe_stack_3->SetBinContent(9,2);
   hFe_stack_3->SetBinContent(35,2);
   hFe_stack_3->SetBinContent(62,2);
   hFe_stack_3->SetBinContent(76,4);
   hFe_stack_3->SetBinContent(77,202);
   hFe_stack_3->SetBinContent(78,100);
   hFe_stack_3->SetBinContent(79,26);
   hFe_stack_3->SetBinContent(80,24);
   hFe_stack_3->SetBinContent(81,14);
   hFe_stack_3->SetBinContent(82,2);
   hFe_stack_3->SetBinContent(83,4);
   hFe_stack_3->SetBinContent(93,2);
   hFe_stack_3->SetEntries(384);

   ci = TColor::GetColor("#0000ff");
   hFe_stack_3->SetLineColor(ci);
   hFe_stack_3->SetLineWidth(2);
   hFe_stack_3->GetXaxis()->SetTitle("Fact_ex/tFe.Fact_ex");
   hFe_stack_3->GetXaxis()->SetRange(1,100);
   hFe_stack_3->GetXaxis()->SetLabelFont(22);
   hFe_stack_3->GetXaxis()->SetLabelSize(0.05);
   hFe_stack_3->GetXaxis()->SetTitleSize(0.05);
   hFe_stack_3->GetXaxis()->SetTitleFont(22);
   hFe_stack_3->GetYaxis()->SetLabelFont(22);
   hFe_stack_3->GetYaxis()->SetLabelSize(0.05);
   hFe_stack_3->GetYaxis()->SetTitleSize(0.05);
   hFe_stack_3->GetYaxis()->SetTitleFont(22);
   hFe_stack_3->GetZaxis()->SetLabelFont(22);
   hFe_stack_3->GetZaxis()->SetLabelSize(0.05);
   hFe_stack_3->GetZaxis()->SetTitleSize(0.05);
   hFe_stack_3->GetZaxis()->SetTitleFont(22);
   ->Add(hFe_stack_3,"");
   ->Draw("nostack");
   
   TLegend *leg = new TLegend(0.333894,0.4230769,0.5222876,0.75,NULL,"brNDC");
   leg->SetTextFont(22);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hC_stack_1","#delta_{D}/#delta_{C}","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("hPb_stack_2","#delta_{D}/#delta_{Pb}","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("hFe_stack_3","#delta_{D}/#delta_{Fe}","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.01,0.945,0.3857611,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetTextFont(22);
   TText *pt_LaTex = pt->AddText("Radiative correction factors");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
